version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    # ports:
    #   - "5678:5678"  # Removed public exposure - access only through Caddy
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-your_secure_password}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your_super_secret_key}
      - N8N_SECURE_COOKIE=true
      - N8N_HOST=n8n.stringbits.com
      - N8N_PROTOCOL=https
      - N8N_PORT=443
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - stringbits_net
    security_opt:
      - no-new-privileges:true
    labels:
      - com.centurylinklabs.watchtower.enable=true

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    # Removed public port - access only through Caddy
    # ports:
    #   - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppassword
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
    labels:
      - com.centurylinklabs.watchtower.enable=true

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    security_opt:
      - no-new-privileges:true
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  n8n_data:
  wordpress_data:
  db_data:

networks:
  stringbits_net:
    external: true
    name: docker-compose_stringbits_net